FROM apache/airflow:2.7.1

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Copy DAGs and plugins
COPY ./dags /opt/airflow/dags
COPY ./plugins /opt/airflow/plugins

# Install the requirements
RUN pip install --no-cache-dir -r /opt/airflow/plugins/requirements.txt 