FROM apache/airflow:latest-python3.12

USER root

# Install system dependencies if needed
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    default-jdk \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$PATH:$JAVA_HOME/bin

# Set lakeFS environment variables
ENV LAKEFS_ENDPOINT=http://lakefs:8000
ENV LAKEFS_ACCESS_KEY=AKIAJBWUDLDFGJY36X3Q
ENV LAKEFS_SECRET_KEY=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

# Download ClickHouse JDBC driver
RUN mkdir -p /opt/airflow/jars && \
    wget -O /opt/airflow/jars/clickhouse-jdbc-0.6.5-all.jar https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.6.5/clickhouse-jdbc-0.6.5-all.jar

# Copy requirements file and setup script
COPY ./dags/extract_lake_fs/extract_lakefs_job.py /opt/airflow/spark/extract_lakefs_job.py
COPY ./dags/extract_lake_fs/lakefs_sense_and_get_commit_operator.py /opt/airflow/spark/lakefs_sense_and_get_commit_operator.py
COPY ./dags/extract_lake_fs/extract_lakefs_dag.py /opt/airflow/spark/extract_lakefs_dag.py
COPY ./dags/extract_lake_fs/transform_data.py /opt/airflow/spark/transform_data.py

COPY ./clickhouse/clickhouse_repository_base.py /opt/airflow/spark/clickhouse/clickhouse_repository_base.py
COPY ./clickhouse/fact_charging_session_repository.py /opt/airflow/spark/clickhouse/fact_charging_session_repository.py

COPY requirements.txt /requirements.txt
COPY setup_connections.sh /setup_connections.sh

# Make the setup script executable
RUN chmod +x /setup_connections.sh

# Switch to airflow user for pip operations
USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir -r /requirements.txt

# Switch back to root for any other operations if needed
USER root