FROM bitnami/spark:latest

# Install curl and set up permissions
USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set up environment variables
# Java configuration
ENV JAVA_HOME=/opt/bitnami/java
# Spark configuration
ENV SPARK_MODE=master
ENV SPARK_HOME=/opt/bitnami/spark
ENV SPARK_NETWORK_TIMEOUT=2000s
ENV SPARK_RPC_MESSAGE_MAXSIZE=1024
ENV SPARK_DRIVER_MEMORY=2g
ENV SPARK_DRIVER_MAXRESULTSIZE=2g
ENV SPARK_EXECUTOR_MEMORY=2g
ENV SPARK_DRIVER_EXTRA_JAVA_OPTIONS=-Dspark.maxRemoteBlockSizeFetchToMem=200m
# Make sure all JAR files are in the classpath
ENV SPARK_CLASSPATH=$SPARK_HOME/jars/*
ENV PATH=$SPARK_HOME/bin:$PATH
ENV PYTHONPATH=${SPARK_HOME}/scripts:${PYTHONPATH}
# Kafka configuration
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:29092
ENV CHARGING_EVENTS_TOPIC=ev_charging_events
# LakeFS configuration
ENV LAKEFS_REPOSITORY=charging-data
ENV LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIAJBWUDLDFGJY36X3Q
ENV LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=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
ENV LAKEFS_ENDPOINT=http://lakefs:8000
ENV LAKEFS_ACCESS_KEY=AKIAJBWUDLDFGJY36X3Q
ENV LAKEFS_SECRET_KEY=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

# Create work directory
WORKDIR $SPARK_HOME

# Install Python packages
COPY ./charging_events_ingestion/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Download dependencies
RUN mkdir -p $SPARK_HOME/jars && \
    # Kafka dependencies
    curl -o $SPARK_HOME/jars/spark-sql-kafka-0-10_2.12-3.3.0.jar \
        https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar && \
    curl -o $SPARK_HOME/jars/kafka-clients-3.3.0.jar \
        https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.3.0/kafka-clients-3.3.0.jar && \
    curl -o $SPARK_HOME/jars/spark-token-provider-kafka-0-10_2.12-3.3.0.jar \
        https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.0/spark-token-provider-kafka-0-10_2.12-3.3.0.jar && \
    curl -o $SPARK_HOME/jars/commons-pool2-2.11.1.jar \
        https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

# Create directory for scripts
RUN mkdir -p $SPARK_HOME/scripts

# Copy the Kafka Spark Streaming script and startup script
# Spark apps/jobs
COPY ./charging_events_ingestion/spark_app.py $SPARK_HOME/scripts/
# Other scripts
COPY ./charging_events_ingestion/charging_events_stream_processor.py $SPARK_HOME/scripts/
COPY ./charging_events_ingestion/lakefs_manager.py $SPARK_HOME/scripts/
# Scripts
COPY ./charging_events_ingestion/start-master.sh $SPARK_HOME/scripts/
COPY ./charging_events_ingestion/spark-defaults.conf $SPARK_HOME/conf/

# Set proper permissions
RUN chmod +x $SPARK_HOME/scripts/start-master.sh && \
    chown -R 1001:root $SPARK_HOME/scripts/ && \
    chown -R 1001:root $SPARK_HOME/jars/

# Switch back to non-root user
USER 1001

# Expose necessary ports
EXPOSE 7077 8080 4040

# Use the startup script as the entry point
CMD ["/opt/bitnami/spark/scripts/start-master.sh"]