FROM alpine:latest

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN apk update
RUN apk upgrade
RUN apk add bash
RUN apk add curl

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]