# Use the official Python base image
FROM python:3.11-slim

ENV SIM_DURATION=100.0
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:29092
ENV CHARGING_EVENTS_TOPIC=ev_charging_events
ENV MONGO_URI=mongodb://User:Pass@mongo-db-node-1:30001,mongo-db-node-2:30002,mongo-db-node-3:30003/Db?replicaSet=replica-set

# Add the app directory to Python path
ENV PYTHONPATH=/app

# Working directory inside the container
WORKDIR /app

# Copy your application code
COPY ./app ./app
COPY ./services ./services
COPY ./repositories ./repositories
COPY ./entities ./entities

RUN pip install --no-cache-dir -r ./app/requirements.txt

# Set the entrypoint / default command to run
CMD ["python", "app/main.py"]