# Use the official Python base image
FROM python:3.11-slim

ENV SIM_DURATION=10
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:29092
ENV CHARGING_EVENTS_TOPIC=ev_charging_events
ENV MONGO_URI=mongodb://User:Pass@mongo-db:27017/Db

# Add the app directory to Python path
ENV PYTHONPATH=/src

COPY ./src/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Set the entrypoint / default command to run
CMD ["python", "src/app/main.py"]