# Use the official Python base image
FROM python:3.11-slim

# Add the app directory to Python path
ENV PYTHONPATH=/src

COPY ./src/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Set the entrypoint / default command to run
CMD ["python", "src/app/main.py"]